### ISSUE TITLE
404 returned by circleci within action

### ISSUE THREAD

**Issue by abhijith-vijayan** [promiseofcake/circleci-trigger-action#186]
returns `Project not found`, was working fine before `v1.4` and `actions/checkout@v3` change

**Comment by saaaab1213** [comment]
Same here

**Comment by theshivamverma** [comment]
Same here

**Comment by abhijith-vijayan** [comment]
@promiseofcake any observations?

**Comment by promiseofcake** [comment]
You might need to rotate your circleci token, they had a large incident and revoked everyone's tokens last week. I'd start there?

**Comment by abhijith-vijayan** [comment]
i think that could be it. closing for now, will re-open if issue is still not resolved. thanks @promiseofcake
