### ISSUE TITLE
Unable to resolve action `promiseofcake/circleci-trigger-action@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by bendavies** [promiseofcake/circleci-trigger-action#199]
Hi there,

since release 1.4.1, we are receiving:
```
Unable to resolve action `promiseofcake/circleci-trigger-action@v1`, unable to find version `v1`
```
when using:
```yaml
uses: promiseofcake/circleci-trigger-action@v1
```

Thanks!

**Comment by promiseofcake** [comment]
Oh no! Okay one moment.

**Comment by promiseofcake** [comment]
Hi I pulled the latest version, please try again and let me know.

**Comment by 46goh** [comment]
@promiseofcake 
Hi there,
we also encountered this issue. I've just re-run the action but it wasn't resolved..

**Comment by himanoa** [comment]
The issue has reappeared, but as a workaround solution, changing the action specified as "v1" in the workflow to "v1.4" fixed the problem.

**Comment by promiseofcake** [comment]
Sorry I forgot about the v1 branch and how that's necessary for GHA. Please try to re-run now, it should be okay I made the v1 branch to be HEAD (which is technically 1.4.1 again)

**Comment by promiseofcake** [comment]
Fixed, and added a regression test, thanks and sorry! 
https://github.com/promiseofcake/circleci-trigger-action/releases/tag/v1.4.2

Please reopen if you have additional issues.
